### ISSUE TITLE
License

### ISSUE THREAD

**Issue by probonopd** [linuxhw/hw-probe-pyqt5-gui#1]
Thanks for improving this utility and making it work on Linux.

Please do not delete the [original](https://github.com/linuxhw/hw-probe-pyqt5-gui/blob/da480e9bea9e94bc26639c8a533797d3dd7354da/Resources/LICENSE#L3) copyright line in https://github.com/linuxhw/hw-probe-pyqt5-gui/blob/main/LICENSE. You may add yours but please do leave the existing one in place.

Maybe just symlink from the one in `Resources/LICENSE`?

Thanks!

**Comment by linuxhw** [comment]
Hi

This is now fixed in both (qt5/6) repositories.

Thanks!
